release:
  gitlab:
    owner: stackvista
    name: devops/sts-toolbox
  name_template: '{{.Tag}}'
brews:
- name: sts-toolbox
  tap:
    owner: stackvista
    name: homebrew-tap
  commit_author:
    name: stackstatebot
    email: sts-admin@stackstate.com
  folder: Formula
  install: |
    bin.install "sts-toolbox"
  test: |
    system "#{bin}/sts-toolbox", "version"
  description: StackState Development Toolbox
  homepage: https://gitlab.com/stackvista/devops/sts-toolbox
  url_template: https://stseuw1-tooling-main-homebrew.s3-eu-west-1.amazonaws.com/{{ .ArtifactName }}
  goarm: "6"
before:
  hooks:
    - go mod download
    - go get github.com/markbates/pkger/cmd/pkger
    - go generate ./...
builds:
- id: sts-toolbox
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - linux_amd64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X gitlab.com/stackstate/cli/cmd.Version={{.Version}}
    -X gitlab.com/stackstate/cli/cmd.Commit={{.Commit}}
    -X gitlab.com/stackstate/cli/cmd.Date={{.Date}}
    -X main.builtBy=goreleaser
  binary: sts-toolbox
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  lang: go
archives:
- id: sts-toolbox
  builds:
  - sts-toolbox
  name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
blobs:
  - provider: s3
    region: eu-west-1
    bucket: stseuw1-tooling-main-homebrew
    ids:
      - sts-toolbox
